// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CityViewController
@end

@implementation FriendsCellController
@end

@implementation UserMessagesController
@end

@implementation UserViewController
@end

@implementation UsersModel
@end

@implementation MainView
@end

