// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CFNetwork/CFNetwork.h>
#import <CoreAudio/CoreAudio.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface CityViewController: UIViewController

@property IBOutlet UITableView * table;

-(IBAction) test:(id) sender;
-(IBAction) viewDidLoad;
-(IBAction) alert_controller;

@end

@interface FriendsCellController: UITableViewCell

@property IBOutlet UIImageView * pimage;
@property IBOutlet UIButton * name;
@property IBOutlet UILabel * hid;

@end

@interface UserMessagesController: UITableViewCell

@property IBOutlet UILabel * name;
@property IBOutlet UILabel * message;
@property IBOutlet UILabel * id;

@end

@interface UserViewController: UIViewController

@property IBOutlet UILabel * nameLabel;
@property IBOutlet UITableView * table;

-(IBAction) viewDidLoad;

@end

@interface UsersModel: NSObject
@end

@interface MainView: UIView
-(IBAction) init;

@end

